[hydrovu]
api_base_url = "https://source-api-base-url.com" # TODO: add source-specific config
token_url    = "https://source-token-url.com"  # TODO: add source-specific config
initial_start_date = "2026-01-01"   # change to limit initial load

[cabq]
api_base_url       = "https://cabq-api-url.com"   # TODO: confirm CABQ API endpoint
initial_start_date = "2026-01-01"   # change to limit initial load

[destination.filesystem]
bucket_url = "gs://your-bucket-name"   # TODO: set your GCS bucket
layout     = "{table_name}/{load_id}.{file_id}.{ext}"

[normalize]
file_format = "parquet"
